### ISSUE TITLE
Undefined function 'db2rt' for input arguments of type 'double'.

### ISSUE THREAD

**Issue by DimitriCroes** [gdalsanto/flutter-echo-modeling#1]
Hello,
im doing a school research on the different ways to synthesise a Flutter echo IR and comparing the options to find the best en why they perform better. Your tool looks very promising.

I want to try and run it on my machine but it gives the following error.

Undefined function 'db2rt' for input arguments of type 'double'.

Error in demo (line 86)
loopRT = db2rt(db(HLoop),L,sampleRate);
 
 Is the missing function a custom made one or is it one from another toolbox i haven't installed.
 If you could tell me what this function does so i can make a compatible replacement (or tell me where to find the orriginal) that would be amazing.

Kind regards
Dimitri

**Comment by gdalsanto** [comment]
Hi Dimitri,

Thank you for opening this issue! Indeed, the function `db2rt` was missing from the folder ./functions. 
I just uploaded it, so now you should be able to run line 86 without any problem. 

Do not hesitate to inform me in case it doesn't work or if you find other errors!  

Btw, the conference paper related to this repository is finally out at this [link](https://www.researchgate.net/publication/363487429_Flutter_Echo_Modeling)! You might find it helpful for your research project. 

Best, 
Gloria

**Comment by DimitriCroes** [comment]
Hello Gloria,

Thank you for you speedy solution to my problem.
It indeed seems to work fine now.
Also thank you for giving me the link of the conference paper.

Best,
Dimitri
